# Generated by Django 3.2.13 on 2022-06-28 11:37

import apps.accounts.models
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    django.contrib.postgres.fields.citext.CICharField(
                        max_length=30,
                        unique=True,
                        validators=[django.core.validators.MaxLengthValidator(30)],
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("staff", models.BooleanField(default=False)),
                ("admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("slug", models.SlugField(unique=True)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.accounts.models.create_profile_pic_name,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Standard", "Standard"),
                            ("Premium", "Premium"),
                            ("Admin", "Admin"),
                        ],
                        default="Standard",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Website",
            fields=[
                ("website_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100, unique=True)),
                ("url", models.URLField(blank=True)),
                ("favicon", models.CharField(blank=True, max_length=500)),
                ("logo", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("social_link_id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.website",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacySettings",
            fields=[
                (
                    "privacy_settings_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("list_subscribtions_public", models.BooleanField(default=True)),
                ("subscribed_sources_public", models.BooleanField(default=True)),
                ("highlighted_articles_public", models.BooleanField(default=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
