# Generated by Django 3.2.13 on 2022-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('full_company_name', models.CharField(max_length=100)),
                ('short_company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
