# Generated by Django 3.2.13 on 2023-02-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20230211_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistKeyword',
            fields=[
                ('wkeyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='watchliststock',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='watchlist_stocks', to='stock.WatchlistKeyword'),
        ),
    ]
