# Generated by Django 3.2.13 on 2023-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20230211_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
