# Generated by Django 3.2.13 on 2023-02-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0005_watchlist_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("portfolio_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("main", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioStock",
            fields=[
                ("pstock_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="watchliststock",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="watchliststock",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="watchliststock",
            name="watchlist",
        ),
        migrations.RenameModel(
            old_name="WatchlistKeyword",
            new_name="PortfolioKeyword",
        ),
        migrations.RenameField(
            model_name="portfoliokeyword",
            old_name="wkeyword_id",
            new_name="pkeyword_id",
        ),
        migrations.DeleteModel(
            name="Watchlist",
        ),
        migrations.DeleteModel(
            name="WatchlistStock",
        ),
        migrations.AddField(
            model_name="portfoliostock",
            name="keywords",
            field=models.ManyToManyField(
                blank=True, related_name="portfolio_stocks", to="stock.PortfolioKeyword"
            ),
        ),
        migrations.AddField(
            model_name="portfoliostock",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stock.portfolio"
            ),
        ),
        migrations.AddField(
            model_name="portfoliostock",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stock.stock"
            ),
        ),
    ]
