# Generated by Django 3.2.13 on 2023-02-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_alter_sourcerating_rating'),
        ('stock', '0006_auto_20230213_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='blacklisted_sources',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_sources_portfolio', to='source.Source'),
        ),
    ]
