# Generated by Django 3.2.13 on 2023-03-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_portfolio_blacklisted_sources'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='portfoliostock',
            constraint=models.UniqueConstraint(fields=('portfolio', 'stock'), name='unique_portfolio_stock'),
        ),
    ]
