# Generated by Django 3.2.13 on 2023-03-04 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliokeyword',
            name='keyword',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
