# Generated by Django 4.0.3 on 2022-04-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banner'),
        ),
    ]
