# Generated by Django 4.0.3 on 2022-04-07 12:10

# import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_profile_banner'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='profile',
    #         name='bio',
    #         field=ckeditor.fields.RichTextField(blank=True, null=True),
    #     ),
    # ]
