# Generated by Django 4.0.3 on 2022-04-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(choices=[('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Medium', 'Medium'), ('Other', 'Other'), ('SeekingAlpha', 'SeekingAlpha'), ('Substack', 'Substack'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], max_length=100)),
                ('url', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
