# Generated by Django 4.0.3 on 2022-04-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('url', models.URLField()),
                ('favicon', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.website'),
        ),
    ]
