# Generated by Django 4.0.3 on 2022-04-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_website_alter_sociallink_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
