# Generated by Django 4.0.3 on 2022-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='color_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
