# Generated by Django 4.0.3 on 2022-04-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_website_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='color_code',
        ),
    ]
