# Generated by Django 4.0.3 on 2022-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_website_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium'), ('Admin', 'Admin')], default='Standard', max_length=50),
        ),
    ]
