# Generated by Django 4.0.3 on 2022-04-26 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_privacysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacysettings',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
