# Generated by Django 4.0.3 on 2022-04-30 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_privacysettings_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing', models.BooleanField(default=False)),
                ('preferences', models.BooleanField(default=False)),
                ('statistics', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
