# Generated by Django 4.0.2 on 2022-05-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_cookiesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookiesettings',
            name='profile',
        ),
    ]
