# Generated by Django 3.2.13 on 2022-05-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_cookiesettings_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
