# Generated by Django 3.2.13 on 2022-05-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_website_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CookieSettings',
        ),
    ]
