# Generated by Django 3.2.13 on 2022-06-07 10:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_delete_cookiesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.create_profile_banner_name),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.create_profile_pic_name),
        ),
    ]
