# Generated by Django 3.2.13 on 2022-06-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220607_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_banner',
        ),
    ]
