# Generated by Django 3.2.13 on 2022-06-22 13:49

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_profile_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=30, unique=True, validators=[django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
