# Generated by Django 3.2.13 on 2022-06-22 17:25

import accounts.validators
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=30, unique=True, validators=[django.core.validators.MaxLengthValidator(30), accounts.validators.validate_domain_available]),
        ),
    ]
