# Generated by Django 4.0.3 on 2022-04-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0030_list_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250, unique=True)),
                ('status', models.CharField(choices=[('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Under Review', max_length=50)),
                ('reason_for_decline', models.CharField(blank=True, choices=[('Not enough depth', 'Not enough depth'), ('Not investment related', 'Not investment related')], max_length=250)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sector')),
            ],
        ),
    ]
