# Generated by Django 4.0.3 on 2022-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesuggestion',
            name='suggestion_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
