# Generated by Django 4.0.3 on 2022-04-24 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_sourcesuggestion_suggestion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSuggestion',
            fields=[
                ('feature_suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_part', models.CharField(max_length=100)),
                ('suggestion', models.CharField(max_length=200)),
                ('explanation', models.TextField(max_length=10000)),
                ('reporting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('bug_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=200)),
                ('explanation', models.TextField(max_length=10000)),
                ('reporting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
