# Generated by Django 4.0.3 on 2022-04-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0003_featuresuggestion_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcesuggestion',
            name='reporting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
