# Generated by Django 3.2.13 on 2022-06-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_sourcesuggestion_reporting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='reporting_user',
        ),
        migrations.RemoveField(
            model_name='featuresuggestion',
            name='reporting_user',
        ),
        migrations.RemoveField(
            model_name='sourcesuggestion',
            name='reason_for_decline',
        ),
        migrations.RemoveField(
            model_name='sourcesuggestion',
            name='reporting_user',
        ),
        migrations.RemoveField(
            model_name='sourcesuggestion',
            name='status',
        ),
    ]
