# Generated by Django 3.2.13 on 2022-06-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_remove_sourcesuggestion_suggestion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_email', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField(max_length=10000)),
            ],
        ),
    ]
