# Generated by Django 3.2.13 on 2022-06-28 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0001_initial'),
        ('list', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.list')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='source.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('notification_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('user_has_seen', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.notification')),
            ],
        ),
    ]
