# Generated by Django 3.2.13 on 2022-08-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='keyword',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
