# Generated by Django 3.2.13 on 2022-09-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_notification_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmessage',
            options={'ordering': ('-date',)},
        ),
    ]
