# Generated by Django 3.2.13 on 2022-09-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('home', '0004_alter_notificationmessage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='list',
        ),
        migrations.AddField(
            model_name='notification',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
