# Generated by Django 3.2.13 on 2023-03-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220902_1245'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'source'), name='unique_source_notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'keyword'), name='unique_keyword_notification'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'stock'), name='unique_stock_notification'),
        ),
        migrations.AddConstraint(
            model_name='notificationmessage',
            constraint=models.UniqueConstraint(fields=('notification', 'article'), name='unique_notification_message'),
        ),
    ]
