# Generated by Django 3.2.13 on 2023-03-07 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_trendingtopiccontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('source', '0009_alter_sourcerating_rating'),
        ('home', '0006_auto_20230304_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('interested_sectors', models.JSONField(default=dict)),
                ('last_content_update', models.DateTimeField()),
                ('content', models.ManyToManyField(blank=True, related_name='feed_content', to='article.Article')),
                ('recommended_sources', models.ManyToManyField(blank=True, related_name='feed_sources', to='source.Source')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
