# Generated by Django 4.0.3 on 2022-03-23 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserCategory',
            fields=[
                ('browser_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('favicon_path', models.CharField(max_length=500)),
                ('paywall', models.CharField(choices=[('Yes', 'Yes'), ('Semi', 'Semi'), ('No', 'No')], default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BrowserSource',
            fields=[
                ('browser_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.browsercategory')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.source')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(unique=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.source')),
            ],
        ),
    ]
