# Generated by Django 4.0.3 on 2022-03-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='domain',
            field=models.CharField(max_length=100),
        ),
    ]
