# Generated by Django 4.0.3 on 2022-03-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
