# Generated by Django 4.0.3 on 2022-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_source_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='favicon_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
