# Generated by Django 4.0.2 on 2022-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_source_favicon_path_alter_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('sources', models.ManyToManyField(related_name='lists', to='home.Source')),
            ],
        ),
    ]
