# Generated by Django 4.0.2 on 2022-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='lists', to='home.Source'),
        ),
    ]
