# Generated by Django 4.0.3 on 2022-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_list_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sources', models.ManyToManyField(blank=True, related_name='sectors', to='home.source')),
            ],
        ),
    ]
