# Generated by Django 4.0.3 on 2022-03-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='content_type',
            field=models.CharField(choices=[('Articles', 'Articles'), ('Sources', 'Sources')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
