# Generated by Django 4.0.2 on 2022-03-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_list_content_type_list_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='website',
            field=models.CharField(choices=[('Medium', 'Medium'), ('SeekingAlpha', 'SeekingAlpha'), ('Substack', 'Substack'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='home.Source'),
        ),
    ]
