# Generated by Django 4.0.2 on 2022-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_source_website_alter_sector_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='website',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Other', 'Other'), ('SeekingAlpha', 'SeekingAlpha'), ('Substack', 'Substack'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], default='None', max_length=15),
        ),
    ]
