# Generated by Django 4.0.2 on 2022-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_source_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='main_website_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='website',
            field=models.CharField(choices=[('Medium', 'Medium'), ('Other', 'Other'), ('SeekingAlpha', 'SeekingAlpha'), ('Substack', 'Substack'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], default='None', max_length=100),
        ),
    ]
