# Generated by Django 4.0.3 on 2022-04-01 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_list_main_website_source_alter_source_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 11, 58, 26, 626195, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
