# Generated by Django 4.0.3 on 2022-04-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='about_text',
            field=models.TextField(blank=True),
        ),
    ]
