# Generated by Django 4.0.3 on 2022-04-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_source_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
