# Generated by Django 4.0.3 on 2022-04-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_article_like_alter_list_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
