# Generated by Django 4.0.3 on 2022-04-08 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_list_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscriber_source', to=settings.AUTH_USER_MODEL),
        ),
    ]
