# Generated by Django 4.0.3 on 2022-04-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_source_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='list_pic',
            field=models.ImageField(blank=True, null=True, upload_to='list_pic'),
        ),
    ]
