# Generated by Django 4.0.3 on 2022-04-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_list_list_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browsersource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='browsersource',
            name='source',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='list_id',
            new_name='sector_id',
        ),
        migrations.DeleteModel(
            name='BrowserCategory',
        ),
        migrations.DeleteModel(
            name='BrowserSource',
        ),
    ]
