# Generated by Django 4.0.3 on 2022-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_browsersource_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='top_source',
            field=models.BooleanField(default=False),
        ),
    ]
