# Generated by Django 4.0.3 on 2022-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_source_top_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='sources',
        ),
        migrations.AddField(
            model_name='source',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='home.sector'),
        ),
        migrations.AlterField(
            model_name='list',
            name='content_type',
            field=models.CharField(choices=[('All', 'All'), ('Articles', 'Articles'), ('Sources', 'Sources')], default='None', max_length=10),
        ),
    ]
