# Generated by Django 4.0.3 on 2022-04-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_sourcerating_listrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listrating',
            old_name='score',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='sourcerating',
            old_name='score',
            new_name='rating',
        ),
    ]
