# Generated by Django 4.0.3 on 2022-04-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_highlightedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles_list', to='home.article'),
        ),
    ]
