# Generated by Django 4.0.3 on 2022-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_list_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
