# Generated by Django 4.0.3 on 2022-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_sector_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
