# Generated by Django 4.0.3 on 2022-04-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_sector_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlightedarticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.article'),
        ),
    ]
