# Generated by Django 4.0.3 on 2022-04-23 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0033_alter_highlightedarticle_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalArticle',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('pub_date', models.DateField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='highlightedarticle',
            name='external_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.externalarticle'),
        ),
    ]
