# Generated by Django 4.0.3 on 2022-04-24 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0034_externalarticle_highlightedarticle_external_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_has_seen', models.BooleanField(default=False)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.list')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
