# Generated by Django 4.0.3 on 2022-04-24 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0035_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('external_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ManyToManyField(blank=True, related_name='external_sectors', to='home.sector')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='highlightedarticle',
            name='external_article',
        ),
        migrations.DeleteModel(
            name='ExternalArticle',
        ),
        migrations.AddField(
            model_name='article',
            name='external_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.externalsource'),
        ),
    ]
