# Generated by Django 4.0.2 on 2022-05-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_list_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsource',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='external_sectors', to='home.Sector'),
        ),
        migrations.AlterField(
            model_name='list',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles_list', to='home.Article'),
        ),
        migrations.AlterField(
            model_name='source',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='sectors', to='home.Sector'),
        ),
    ]
