# Generated by Django 3.2.13 on 2022-05-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_article_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_has_seen',
        ),
        migrations.AlterField(
            model_name='article',
            name='external_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.externalsource'),
        ),
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('notification_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_has_seen', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.notification')),
            ],
        ),
    ]
