# Generated by Django 3.2.13 on 2022-05-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_notificationmessage_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
