# Generated by Django 3.2.13 on 2022-05-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_notificationmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
