# Generated by Django 3.2.13 on 2022-05-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_list_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
