# Generated by Django 3.2.13 on 2022-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_article_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
