# Generated by Django 3.2.13 on 2022-05-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_source_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='domain',
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
