# Generated by Django 3.2.13 on 2022-05-23 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_cookiesettings_profile'),
        ('home', '0051_auto_20220522_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.website'),
        ),
    ]
