# Generated by Django 3.2.13 on 2022-05-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_source_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='website',
        ),
    ]
