# Generated by Django 3.2.13 on 2022-05-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_source_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='site',
            new_name='website',
        ),
    ]
