# Generated by Django 3.2.13 on 2022-05-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_rename_site_source_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_article_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
