# Generated by Django 3.2.13 on 2022-05-29 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_source_last_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_article_title',
        ),
        migrations.RemoveField(
            model_name='source',
            name='sector',
        ),
        migrations.AddField(
            model_name='source',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sector'),
        ),
    ]
