# Generated by Django 3.2.13 on 2022-06-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20220529_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsource',
            name='sector',
        ),
        migrations.AddField(
            model_name='externalsource',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sector'),
        ),
    ]
