# Generated by Django 3.2.13 on 2022-06-07 10:04

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20220602_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalsource',
            name='sector',
        ),
        migrations.AlterField(
            model_name='list',
            name='list_pic',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.create_list_pic_name),
        ),
    ]
