# Generated by Django 3.2.13 on 2022-06-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20220607_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='ammount_of_ratings',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
