# Generated by Django 3.2.13 on 2022-06-22 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20220607_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MaxLengthValidator(40)]),
        ),
    ]
