# Generated by Django 3.2.13 on 2022-09-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ('name',)},
        ),
    ]
