# Generated by Django 3.2.13 on 2023-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0002_alter_sector_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='sim_sectors',
            field=models.ManyToManyField(blank=True, related_name='similiar_to', to='sector.Sector'),
        ),
    ]
