# Generated by Django 3.2.13 on 2022-06-28 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('bug_report_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('type', models.CharField(max_length=200)),
                ('explanation', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_email', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('explanation', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureSuggestion',
            fields=[
                ('feature_suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_part', models.CharField(max_length=100)),
                ('suggestion', models.CharField(max_length=200)),
                ('explanation', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSuggestion',
            fields=[
                ('source_suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250, unique=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sector.sector')),
            ],
        ),
    ]
