# Generated by Django 3.2.13 on 2023-03-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugReport',
        ),
        migrations.DeleteModel(
            name='FeatureSuggestion',
        ),
        migrations.DeleteModel(
            name='SourceSuggestion',
        ),
    ]
