# Generated by Django 3.2.13 on 2023-02-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_list_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
