# Generated by Django 3.2.13 on 2023-02-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_list_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='hcontent',
            field=models.BooleanField(default=False),
        ),
    ]
