# Generated by Django 3.2.13 on 2023-02-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_list_hcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='ammount_of_ratings',
        ),
        migrations.RemoveField(
            model_name='list',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='list',
            name='hcontent',
        ),
        migrations.RemoveField(
            model_name='list',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='list',
            name='main_website_source',
        ),
        migrations.RemoveField(
            model_name='list',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='list',
            name='subscribers',
        ),
        migrations.DeleteModel(
            name='ListRating',
        ),
    ]
