# Generated by Django 3.2.13 on 2023-03-04 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20230226_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
