# Generated by Django 3.2.13 on 2022-07-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingTopicArticle',
            fields=[
                ('tta_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
        migrations.CreateModel(
            name='MacroTweets',
            fields=[
                ('mt_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyCrisisTweet',
            fields=[
                ('ect_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
        migrations.CreateModel(
            name='AudioOfTheWeek',
            fields=[
                ('auotw_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleOfTheWeek',
            fields=[
                ('arotw_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
