# Generated by Django 3.2.13 on 2022-07-07 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articleoftheweek_audiooftheweek_energycrisistweet_macrotweets_trendingtopicarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetType',
            fields=[
                ('tweet_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Link', 'Link'), ('Retweet', 'Retweet')], default='None', max_length=10)),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tweet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.tweettype'),
        ),
    ]
