# Generated by Django 3.2.13 on 2022-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220707_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweettype',
            name='type',
            field=models.CharField(choices=[('Image', 'Image'), ('Link', 'Link'), ('Retweet', 'Retweet'), ('Basic', 'Basic')], default='None', max_length=10),
        ),
    ]
