# Generated by Django 3.2.13 on 2022-07-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_tweettype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='external_source',
        ),
    ]
