# Generated by Django 3.2.13 on 2022-08-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20220730_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweettype',
            name='initial_tweet_img_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
