# Generated by Django 3.2.13 on 2022-08-24 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_delete_externalsource'),
        ('article', '0008_tweettype_initial_tweet_img_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiooftheweek',
            name='article',
        ),
        migrations.RemoveField(
            model_name='energycrisistweet',
            name='article',
        ),
        migrations.RemoveField(
            model_name='macrotweets',
            name='article',
        ),
        migrations.RemoveField(
            model_name='trendingtopicarticle',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.source'),
        ),
        migrations.DeleteModel(
            name='ArticleOfTheWeek',
        ),
        migrations.DeleteModel(
            name='AudioOfTheWeek',
        ),
        migrations.DeleteModel(
            name='EnergyCrisisTweet',
        ),
        migrations.DeleteModel(
            name='MacroTweets',
        ),
        migrations.DeleteModel(
            name='TrendingTopicArticle',
        ),
    ]
