# Generated by Django 3.2.13 on 2022-08-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20220824_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tweet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweet', to='article.tweettype'),
        ),
    ]
