# Generated by Django 3.2.13 on 2023-03-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='highlightedarticle',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_highlighted'),
        ),
    ]
