# Generated by Django 3.2.13 on 2023-05-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_trendingtopiccontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
