# Generated by Django 3.2.13 on 2023-06-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_portfoliokeyword_keyword'),
        ('article', '0015_alter_article_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPitch',
            fields=[
                ('stock_pitch_id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
