# Generated by Django 3.2.13 on 2023-07-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_stockpitch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpitch',
            name='stock',
        ),
    ]
