# Generated by Django 3.2.13 on 2022-06-28 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sector', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('favicon_path', models.CharField(blank=True, max_length=500)),
                ('paywall', models.CharField(choices=[('Yes', 'Yes'), ('Semi', 'Semi'), ('No', 'No')], default='None', max_length=10)),
                ('top_source', models.BooleanField(default=False)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ammount_of_ratings', models.IntegerField(default=0, null=True)),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sector.sector')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscriber_source', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.website')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRating',
            fields=[
                ('source_rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('external_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('website_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
