# Generated by Django 3.2.13 on 2022-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='news',
            field=models.BooleanField(default=False),
        ),
    ]
