# Generated by Django 3.2.13 on 2022-07-21 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_source_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalsource',
            old_name='website_name',
            new_name='website_link',
        ),
    ]
