# Generated by Django 3.2.13 on 2022-07-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_remove_article_external_source'),
        ('source', '0003_rename_website_name_externalsource_website_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalSource',
        ),
    ]
