# Generated by Django 3.2.13 on 2022-09-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_delete_externalsource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('name',)},
        ),
    ]
