# Generated by Django 3.2.13 on 2023-01-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_alter_source_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='source',
            name='news',
        ),
        migrations.AddField(
            model_name='source',
            name='content_type',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Semi', 'Semi'), ('No', 'No')], default='Commentary', max_length=15),
        ),
        migrations.AddField(
            model_name='source',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='source_tags', to='source.SourceTag'),
        ),
    ]
