# Generated by Django 3.2.13 on 2023-01-05 22:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20230102_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
