# Generated by Django 3.2.13 on 2023-03-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_alter_sourcerating_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sourcerating',
            constraint=models.UniqueConstraint(fields=('user', 'source'), name='unique_rating'),
        ),
    ]
