# Generated by Django 3.2.13 on 2023-03-04 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_sourcerating_unique_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcerating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
