# Generated by Django 3.2.13 on 2023-03-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_source_sim_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='sim_sources',
        ),
    ]
