# Generated by Django 3.2.13 on 2023-03-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_source_sim_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='sim_sources',
            field=models.ManyToManyField(blank=True, related_name='similiar_to', to='source.Source'),
        ),
    ]
