# Generated by Django 3.2.13 on 2023-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_alter_source_sim_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='content_type',
            field=models.CharField(choices=[('Analysis', 'Analysis'), ('Commentary', 'Commentary'), ('News', 'News')], default='Commentary', max_length=15),
        ),
    ]
