# Generated by Django 3.2.13 on 2023-05-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_alter_source_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcetag',
            options={'ordering': ('name',)},
        ),
    ]
