# Generated by Django 3.2.13 on 2023-06-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_alter_sourcetag_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='alt_feed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
