full_fillerwords = [
    "The Open Joint Stock Company ",
    " Class D",
    " American Depositary Shares each representing one-fifth of an Ordinary Share",
    " common stock",
    " Warrants",
    " Ordinary Shares",
    " ordinary share",
    " each representing 1/1000th interest in a share of Series I Non-CumulativePreferred Stock",
    "Dep Shs Repstg 1/40th Perp Pfd Ser G",
    " Fixed-to-Floating Rate Non-Cumulative Perpetual Preferred Stock Series D",
    " 1 Unit",
    " Unit",
    " each representing one",
    " Ordinary Share",
    " Class A",
    " Voting Common Stock",
    " New Switzerland Registered Shares",
    " Series D Cumulative Preferred Stock",
    " Class B Preferred Stock",
    " Ordinary Shares",
    " American Depositary Shares",
    " American Depositary Share",
    " Depositary Shares",
    " Common Shares",
    " of Beneficial Interest",
    " Warrant",
    " Warrants",
    " Common stock",
    " Common Shares",
    " Common Stock",
    " Series A",
    " Corp.s",
    " N.V.s",
    " American depositary shares each representing two ordinary shares",
    " AGs-fifth of an",
    " Redeemable Preferred Stock",
    " expiring",
    " and Class B Variable Voting Shares",
    " Right",
    ". 1s",
]

short_fillerwords = [
    " & Co.",
    " Company",
    " Inc.",
    " Inc",
    " Corporation",
    "  & Co.",
    " Group",
    " Holdings",
    " Holding",
    " Ltd",
    " plc",
    " inc",
    " S.A.B. de C.V.",
    " S.A. de C.V.",
    ".com",
    " Technology",
    " Corp",
    " (The)",
    " International",
    " Limited",
    " N.A.",
    " N.V.",
    " Technologies",
    " L.P.",
    " Co.",
    " Incoperated",
    " S.A.",
    " (NJ)",
    " p.l.c.",
    " .s",
    " Public Companys",
    " Companys",
    " S.p.A.s",
    " S.p.A.",
    " B.V.s",
    " Ltd.",
    " Pte. Ltd.",
    " SARL",
    " GmbH",
    " KGaA",
    " AG",
    " AB",
    " ABP",
    " AS",
    " A/S",
    " A/S",
    " A.G.",
    " Bhd.",
    " Corp.",
    " Ltda.",
    " Oyj",
    " P.L.C.",
    " S.L.",
    " S.R.L.",
    " S.A.U.",
    " S.A.S.",
    " Sdn. Bhd.",
    " Sociedad Anonima",
    " Sp. z o.o.",
    " Zrt.",
]

new_fillerwords = [
    " PLC",
    " Bank",
    " Acquistion",
    " Plc",
    " Gold",
    " SA",
    " Enterprise",
    " Services",
    " Bancorp",
    " Resource",
    " Mining & Exploration",
    " Biologics",
    " Capital",
    " NL",
    " Equity Ventures",
    " Property",
    " Realty Trust",
    " Biopharma",
    " Bancshares",
    " Financial",
    " Inc",
    " (publ)",
    " Therapeutics",
    " Entertainment",
    " Energy",
    " SE",
    " Minerals",
    " Discovery",
    " Metals",
    " Pharmaceuticals",
    " Silver",
    " Trust",
    " Medical",
    " REIT",
    " Industry",
    " Industries",
    " Biosciences",
    " S A B de C V",
    " Foods",
    " Health",
    " Global",
    " Healthcare",
    " Lithium",
    " Sciences",
    " Systems",
    " National",
    " Oil",
]
